export const DEFAULT_LANGUAGE = 'en';

export const LANGUAGES = [
  {
    code: 'en',
    label: 'English',
    flagAlt: 'English flag',
  },
  {
    code: 'vi',
    label: 'Việt Nam',
    flagAlt: 'Vietnamese flag',
  },
  {
    code: 'no',
    label: 'Norsk',
    flagAlt: 'Norwegian flag',
  },
];

export const TEXTS = {
  en: {
    brand: {
      name: 'VibeCheck.ai',
      logoAlt: 'VibeCheck.ai logo',
    },
    header: {
      notifications: 'Notifications',
      avatarAlt: 'User avatar',
    },
    sidebar: {
      settings: 'Settings',
      chat: 'Chat',
      history: 'History',
      download: 'Download',
    },
    home: {
      newChat: 'New Chat',
      title: 'Check the quality',
      subtitle: "Of source code generated by 'vibe coding'.",
      stepOne: 'Step 1: Paste the GitHub link to check the size of the source code',
      repoPlaceholder: 'github.com/owner/repo',
      submitRepo: 'Submit repository link',
    },
    footer: {
      copyright: '2026 VibeCheck.ai',
      privacyPolicy: 'Privacy Policy',
      termsOfService: 'Terms of Service',
      cookieSettings: 'Cookie Settings',
      language: 'Language',
    },
  },
  vi: {
    brand: {
      name: 'VibeCheck.ai',
      logoAlt: 'Logo VibeCheck.ai',
    },
    header: {
      notifications: 'Thông báo',
      avatarAlt: 'Ảnh đại diện người dùng',
    },
    sidebar: {
      settings: 'Cài đặt',
      chat: 'Trò chuyện',
      history: 'Lịch sử',
      download: 'Tải xuống',
    },
    home: {
      newChat: 'Trò chuyện mới',
      title: 'Kiểm tra chất lượng',
      subtitle: "Của mã nguồn được tạo bởi 'vibe coding'.",
      stepOne: 'Bước 1: Dán liên kết GitHub để kiểm tra kích thước mã nguồn',
      repoPlaceholder: 'github.com/owner/repo',
      submitRepo: 'Gửi liên kết kho mã',
    },
    footer: {
      copyright: '2026 VibeCheck.ai',
      privacyPolicy: 'Chính sách bảo mật',
      termsOfService: 'Điều khoản dịch vụ',
      cookieSettings: 'Cài đặt cookie',
      language: 'Ngôn ngữ',
    },
  },
  no: {
    brand: {
      name: 'VibeCheck.ai',
      logoAlt: 'VibeCheck.ai-logo',
    },
    header: {
      notifications: 'Varsler',
      avatarAlt: 'Brukeravatar',
    },
    sidebar: {
      settings: 'Innstillinger',
      chat: 'Chat',
      history: 'Historikk',
      download: 'Last ned',
    },
    home: {
      newChat: 'Ny chat',
      title: 'Sjekk kvaliteten',
      subtitle: "På kildekode generert av 'vibe coding'.",
      stepOne: 'Steg 1: Lim inn GitHub-lenken for å sjekke størrelsen på kildekoden',
      repoPlaceholder: 'github.com/owner/repo',
      submitRepo: 'Send inn depotlenke',
    },
    footer: {
      copyright: '2026 VibeCheck.ai',
      privacyPolicy: 'Personvernerklæring',
      termsOfService: 'Vilkår for bruk',
      cookieSettings: 'Informasjonskapsler',
      language: 'Språk',
    },
  },
};
