export const RESULT_MOCK = {
  repository: 'TagKrj/UTTQ_Web',
  repositoryUrl: 'https://github.com/TagKrj/UTTQ_Web',
  analyzedAt: '24/3/2025',
  grade: 'A',
  score: 92,
  headline: 'Strong architecture',
  summary: 'Clean modular code with a few areas to improve',
  shortReview: [
    'Solid codebase with room for refinementSolid codebase with room for refinement',
    'Solid codebase with room for refinement',
    'Solid codebase with room for refinement',
  ],
  analysisType: 'Default',
  codeSmells: [
    {
      id: 1,
      filePath: 'src/App.js',
      type: 'Example smell',
      description: 'Example description',
      line: '10-15',
      severity: 'Medium',
    },
    {
      id: 2,
      filePath: 'src/App.js',
      type: 'Example smell',
      description: 'Example description',
      line: '10-15',
      severity: 'Low',
    },
    {
      id: 3,
      filePath: 'src/App.js',
      type: 'Example smell',
      description: 'Example descriptiondsdsdssds sdsdsdsdsdsds',
      line: '10-15',
      severity: 'High',
    },
    {
      id: 4,
      filePath: 'src/App.js',
      type: 'Example smell',
      description: 'Example description',
      line: '10-15',
      severity: 'Medium',
    },
    {
      id: 5,
      filePath: 'src/App.js',
      type: 'Example smell',
      description: 'Example description',
      line: '10-15',
      severity: 'Medium',
    },
    {
      id: 6,
      filePath: 'src/App.js',
      type: 'Example smell',
      description: 'Example description with a longer explanation that should be truncated in the table but visible in the detail popup.',
      line: '10-15',
      severity: 'Medium',
    },
    {
      id: 7,
      filePath: 'src/App.js',
      type: 'Example smell',
      description: 'Example description',
      line: '10-15',
      severity: 'Medium',
    },
    {
      id: 8,
      filePath: 'src/components/VeryLongComponentName.jsx',
      type: 'Complex conditional rendering',
      description: 'The render function contains nested conditions and repeated UI branches that make behavior difficult to reason about.',
      line: '42-88',
      severity: 'High',
    },
    {
      id: 9,
      filePath: 'src/hooks/useRepositoryAnalysis.js',
      type: 'Duplicated data mapping',
      description: 'Several response mapping branches repeat the same fallback logic and can drift when backend fields change.',
      line: '12-39',
      severity: 'Low',
    },
  ],
  securityIssues: [
    {
      id: 1,
      filePath: 'src/App.js',
      type: 'Example smell',
      description: 'Example description',
      line: '10-15',
      severity: 'Medium',
    },
    {
      id: 2,
      filePath: 'src/App.js',
      type: 'Example smell',
      description: 'Example description',
      line: '10-15',
      severity: 'Low',
    },
    {
      id: 3,
      filePath: 'src/App.js',
      type: 'Example smell',
      description: 'Example descriptiondsdsdssds sdsdsdsdsdsds',
      line: '10-15',
      severity: 'High',
    },
    {
      id: 4,
      filePath: 'src/App.js',
      type: 'Example smell',
      description: 'Example description',
      line: '10-15',
      severity: 'Medium',
    },
    {
      id: 5,
      filePath: 'src/App.js',
      type: 'Example smell',
      description: 'Example description',
      line: '10-15',
      severity: 'Medium',
    },
    {
      id: 6,
      filePath: 'src/auth/tokenStorage.js',
      type: 'Token storage',
      description: 'Access tokens are retained in a browser-accessible location for longer than necessary after analysis finishes.',
      line: '21-33',
      severity: 'High',
    },
    {
      id: 7,
      filePath: 'src/api/client.js',
      type: 'Missing timeout',
      description: 'Outbound requests do not set a timeout and can leave the interface waiting indefinitely on unstable networks.',
      line: '7-20',
      severity: 'Medium',
    },
    {
      id: 8,
      filePath: 'src/config/env.js',
      type: 'Verbose error details',
      description: 'Configuration errors expose internal environment key names in UI-facing messages.',
      line: '3-16',
      severity: 'Low',
    },
  ],
};

export function buildResultMock(analysis) {
  const normalizedRepoUrl = analysis?.repoUrl?.replace(/^https?:\/\//, '') || RESULT_MOCK.repository;
  const repositoryUrl = normalizedRepoUrl.startsWith('github.com') ? `https://${normalizedRepoUrl}` : `https://github.com/${normalizedRepoUrl}`;

  return {
    ...RESULT_MOCK,
    repository: normalizedRepoUrl.replace(/^github\.com\//, ''),
    repositoryUrl,
    fileCount: analysis?.fileCount ?? 1934,
    size: analysis?.size ?? 'Large',
    sizeTone: analysis?.sizeTone ?? 'danger',
    codeSmellCount: RESULT_MOCK.codeSmells.length,
    securityCount: RESULT_MOCK.securityIssues.length,
  };
}
